import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Portofolio",
  description: "Generated by create next app",
};

import Link from 'next/link';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}>
        <nav className="fixed top-12 left-1/2 transform -translate-x-1/2 flex items-center justify-between rounded-full border border-white/10 bg-white/5 px-6 py-4 backdrop-blur w-[90%] max-w-2xl z-50">
          <div className="flex items-center gap-3">
            <Link href="/" className="font-semibold tracking-tight hover:text-white">
              My Portofolio
            </Link>
          </div>
          <div className="flex gap-6 text-sm text-white/80">
            <Link href="/" className="hover:text-white">
              Home
            </Link>
            <Link href="/about" className="hover:text-white">
              About
            </Link>
            <Link href="#" className="hover:text-white">
              My Skill
            </Link>
            <Link href="#" className="hover:text-white">
              My Project
            </Link>
          </div>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
